### ISSUE TITLE
Why not as a module?

### ISSUE THREAD

**Issue by marcharding** [EllisV/oxid-console#25]
Is there a reason why the oxid-console ist not released as a module? It makes source control much easier and cleaner (i pull external modules as git submodules).

One could easily put some kind of auto-activation in the oxid-entry point. I just did that and converted the structure to a module, which works fine for me.

If not as a module, i really think this should be in the oxid core. It is an essential function for automatic deployments...

**Comment by EllisV** [comment]
Hello @marcharding 

There were several reasons why oxid-console didn't go as a module:
* It isn't an actual module. Modules should be looked as patches, which give actual shop (I mean web application) additional functionality
* OXID console was created to be a part of automatic deployment package which includes module enabling, recreating module extension chain and etc. We couldn't have full control of module handling if it would be module itself
* Idea was to have this in the core package at some point

OXID Console had an update mechanism in earlier versions but it has been removed in favor to deprecate using oxid console. I am now working on a project called [oxid-standard](https://github.com/EllisV/oxid-standard) which includes having console application aswell.

**Comment by marcharding** [comment]
Hello EllisV,

just wanted to let you know that i started my own cli tool (inspired by your work and the magerun project) for oxid which is completely decoupled and based on the symfony console component. 

Its quite easy to use (just a phar file) and also has a cli based installer for oxid.

https://github.com/marcharding/oxrun
